// Generated by build script, do not edit!
#ifndef RC_INVOKED
#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2022 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/buildslave/unity/build";

    extern const char* const UnityVersion = "2021.2.14f1";
    extern const char* const UnityVersionDigits = "2021.2.14";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 2;
    extern const UInt32 UnityVersionMinor = 14;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2021.2.14f1_bcb93e5482d2";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.2.14f1_bcb93e5482d2";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.2.14f1 (bcb93e5482d2)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 12368190;

    extern const UInt64 UnityVersionDate = 1645533509;
    extern const char* const UnityVersionBranch = "2021.2/staging";
    extern const char* const UnityVersionDisplay = "2021.2.14f1";
    extern const char* const UnityVersionDisplay_Verbose = "2021.2.14f1.4469";
    extern const char* const UnityVersionRevision = "bcb93e5482d2";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.2.14f1 (bcb93e5482d2)";
    extern const wchar_t* const L_UnityVersion = L"2021.2.14f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2022 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 2
    #define UNITY_VERSION_MIN 14
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2021.2.14f1_bcb93e5482d2"
    #define UNITY_VERSION_PARENS_HASH "2021.2.14f1 (bcb93e5482d2)"
    #define UNITY_VERSION_BLD 12368190
    #define UNITY_VERSION_WIN "2021.2.14.12368190"

#endif // !RC_INVOKED
